import { MaterialIcons } from "@expo/vector-icons";
import { router, type Href } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useAdminAuth } from "@/admin/AdminAuthProvider"; import { createAdminVehicle } from "@/admin/api"; import { hasCapability } from "@/admin/capabilities"; import { AdminButton, AdminCard, AdminGate, AdminScreen } from "@/admin/AdminShell"; import { useAppTheme } from "@/components/ThemeProvider"; import { radii, type AppColors } from "@/constants/theme";
const STATUSES = ["AVAILABLE", "UNAVAILABLE", "MAINTENANCE", "INACTIVE"];
export default function NewVehicleScreen() { return <AdminGate><NewVehicle /></AdminGate>; }
function NewVehicle() { const { request, user } = useAdminAuth(); const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); const [make, setMake] = useState(""); const [model, setModel] = useState(""); const [year, setYear] = useState(String(new Date().getFullYear())); const [seats, setSeats] = useState("5"); const [rate, setRate] = useState(""); const [deposit, setDeposit] = useState(""); const [status, setStatus] = useState("AVAILABLE"); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const allowed = Boolean(user && hasCapability(user.role, "vehicles.write"));
  const save = async () => { const parsedYear = Number(year); const parsedSeats = seats.trim() ? Number(seats) : null; const parsedRate = Number(rate.replaceAll(",", "")); const parsedDeposit = Number(deposit.replaceAll(",", "")); if (!make.trim() || !model.trim() || !Number.isInteger(parsedYear) || parsedRate <= 0 || parsedDeposit < 0 || (parsedSeats !== null && !Number.isInteger(parsedSeats))) { setError("Enter a valid make, model, year, seats, daily rate, and deposit."); return; } setBusy(true); setError(""); try { const vehicle = await createAdminVehicle(request, { make: make.trim(), model: model.trim(), year: parsedYear, seatCount: parsedSeats, dailyRateJmd: parsedRate, depositJmd: parsedDeposit, status }); router.replace(`/admin/vehicles/${vehicle.id}` as Href); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Unable to create vehicle."); } finally { setBusy(false); } };
  if (!allowed) return <AdminScreen back title="Workspace unavailable" subtitle="Vehicle creation requires an administrator role." />;
  return <AdminScreen back eyebrow="ADD TO FLEET" title="New vehicle" subtitle="New vehicles stay private until media and public listing details are intentionally completed.">{error ? <View style={styles.error}><MaterialIcons name="error-outline" size={20} color={colors.danger} /><Text style={styles.errorText}>{error}</Text></View> : null}<AdminCard><Text style={styles.title}>Vehicle essentials</Text><Field label="Make *" value={make} onChangeText={setMake} autoCapitalize="words" /><Field label="Model *" value={model} onChangeText={setModel} autoCapitalize="words" /><View style={styles.two}><View style={styles.half}><Field label="Year *" value={year} onChangeText={setYear} keyboardType="number-pad" /></View><View style={styles.half}><Field label="Seats" value={seats} onChangeText={setSeats} keyboardType="number-pad" /></View></View><Field label="Daily rate (JMD) *" value={rate} onChangeText={setRate} keyboardType="number-pad" /><Field label="Deposit (JMD) *" value={deposit} onChangeText={setDeposit} keyboardType="number-pad" /><Text style={styles.fieldLabel}>Configured status</Text><View style={styles.statuses}>{STATUSES.map((item) => <Pressable key={item} onPress={() => setStatus(item)} style={[styles.chip, status === item && styles.chipActive]}><Text style={[styles.chipText, status === item && styles.chipTextActive]}>{humanize(item)}</Text></Pressable>)}</View><View style={styles.privateNotice}><MaterialIcons name="visibility-off" size={18} color={colors.tealDark} /><Text style={styles.privateText}>Private by default. Add approved photos before publishing this vehicle to customers.</Text></View><AdminButton label={busy ? "Adding vehicle…" : "Add vehicle to fleet"} onPress={() => void save()} disabled={busy} icon="add-road" /></AdminCard></AdminScreen>;
}
function Field({ label, ...props }: { label: string } & React.ComponentProps<typeof TextInput>) { const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><TextInput {...props} placeholderTextColor={colors.muted} style={styles.input} /></View>; } function humanize(value: string) { return value.toLowerCase().replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase()); }
const makeStyles = (colors: AppColors) => StyleSheet.create({ title: { color: colors.text, fontSize: 20, fontWeight: "900" }, field: { marginTop: 14 }, fieldLabel: { color: colors.muted, fontSize: 10, fontWeight: "900", marginTop: 14, marginBottom: 7 }, input: { minHeight: 50, paddingHorizontal: 14, borderRadius: radii.md, backgroundColor: colors.surfaceSoft, borderWidth: 1, borderColor: colors.border, color: colors.text, fontSize: 14 }, two: { flexDirection: "row", gap: 10 }, half: { flex: 1 }, statuses: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, chip: { minHeight: 38, paddingHorizontal: 12, borderRadius: radii.pill, justifyContent: "center", borderWidth: 1, borderColor: colors.border }, chipActive: { backgroundColor: colors.teal, borderColor: colors.teal }, chipText: { color: colors.muted, fontSize: 9, fontWeight: "900" }, chipTextActive: { color: colors.white }, privateNotice: { flexDirection: "row", alignItems: "flex-start", gap: 8, padding: 12, borderRadius: radii.md, backgroundColor: colors.cream, marginTop: 16 }, privateText: { flex: 1, color: colors.tealDark, fontSize: 11, lineHeight: 17, fontWeight: "700" }, error: { flexDirection: "row", gap: 8, padding: 13, borderRadius: radii.lg, borderWidth: 1, borderColor: colors.danger, backgroundColor: colors.surface }, errorText: { flex: 1, color: colors.danger, fontSize: 12 }, });
