import { MaterialIcons } from "@expo/vector-icons";
import { randomUUID } from "expo-crypto";
import { router, type Href, useFocusEffect, useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, BackHandler, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { useAdminAuth } from "@/admin/AdminAuthProvider";
import { addAdminBookingPayment, createAdminBooking, fetchAdminAvailableVehicles, fetchAdminBookingLocations, fetchAdminCustomer, fetchAdminInsuranceOption, fetchAdminPricingPreview, fetchMinimumRentalDays, type AdminAvailableVehicle, type AdminBookingCreateInput, type AdminBookingLocation, type AdminInsuranceOption, type AdminManualPaymentInput, type AdminManualPaymentMethod, type AdminPricingPreview } from "@/admin/api";
import { buildLocationSelection, locationFields, locationForType, locationsForSide, prepareBookingCreate, prepareManualPayment, type LocationValues } from "@/admin/adminCreationModel";
import { hasCapability } from "@/admin/capabilities";
import { AdminButton, AdminCard, AdminScreen } from "@/admin/AdminShell";
import { CalendarPicker } from "@/components/CalendarPicker";
import { useAppTheme } from "@/components/ThemeProvider";
import { radii, type AppColors } from "@/constants/theme";

const EMPTY_INSURANCE: AdminInsuranceOption = { enabled: false, planId: null, pricePerDayCents: 0, coverageCents: 0 };
const PAYMENT_METHODS: { value: AdminManualPaymentMethod; label: string }[] = [{ value: "CASH", label: "Cash" }, { value: "BANK_TRANSFER", label: "Bank transfer" }, { value: "POS_CARD", label: "POS / card" }, { value: "CHEQUE", label: "Cheque" }, { value: "OTHER", label: "Other" }];

export function AdminBookingCreateForm() {
  const params = useLocalSearchParams<{ customerId?: string | string[] }>();
  const customerId = Array.isArray(params.customerId) ? params.customerId[0] : params.customerId;
  const { request, user } = useAdminAuth(); const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]);
  const allowed = Boolean(user && hasCapability(user.role, "bookings.write"));
  const [clientRequestId] = useState(() => randomUUID());
  const [customerFullName, setCustomerFullName] = useState(""); const [customerEmail, setCustomerEmail] = useState(""); const [customerPhone, setCustomerPhone] = useState(""); const [customerBlocked, setCustomerBlocked] = useState(false);
  const [pickupDate, setPickupDate] = useState(""); const [dropoffDate, setDropoffDate] = useState(""); const [minimumDays, setMinimumDays] = useState(1);
  const [locations, setLocations] = useState<AdminBookingLocation[]>([]); const [pickupTypeKey, setPickupTypeKey] = useState(""); const [dropoffTypeKey, setDropoffTypeKey] = useState(""); const [pickupValues, setPickupValues] = useState<LocationValues>({}); const [dropoffValues, setDropoffValues] = useState<LocationValues>({});
  const [vehicles, setVehicles] = useState<AdminAvailableVehicle[]>([]); const [vehicleId, setVehicleId] = useState(""); const [insurance, setInsurance] = useState<AdminInsuranceOption>(EMPTY_INSURANCE); const [protectionChoice, setProtectionChoice] = useState<"" | "NONE" | "STANDARD">(""); const [promoCode, setPromoCode] = useState("");
  const [preview, setPreview] = useState<AdminPricingPreview | null>(null); const [previewKey, setPreviewKey] = useState("");
  const [recordPayment, setRecordPayment] = useState(false); const [paymentAmount, setPaymentAmount] = useState(""); const [paymentAmountEdited, setPaymentAmountEdited] = useState(false); const [paymentMethod, setPaymentMethod] = useState<AdminManualPaymentMethod>("CASH"); const [paymentReference, setPaymentReference] = useState(""); const [paymentNote, setPaymentNote] = useState("");
  const [loadingSetup, setLoadingSetup] = useState(true); const [busy, setBusy] = useState<"" | "availability" | "insurance" | "preview" | "create" | "payment">(""); const [error, setError] = useState(""); const [warning, setWarning] = useState(""); const [createdBookingId, setCreatedBookingId] = useState("");

  const dirty = Boolean(customerFullName || customerEmail || customerPhone || pickupDate || dropoffDate || Object.keys(pickupValues).length || Object.keys(dropoffValues).length || vehicleId || promoCode || recordPayment);
  const currentPreviewKey = useMemo(() => JSON.stringify({ customerId: customerId || null, email: customerEmail.trim().toLowerCase(), pickupDate, dropoffDate, vehicleId, protectionChoice, insurancePlanId: protectionChoice === "STANDARD" ? insurance.planId : null, promoCode: promoCode.trim().toUpperCase() }), [customerEmail, customerId, dropoffDate, insurance.planId, pickupDate, promoCode, protectionChoice, vehicleId]);
  const previewCurrent = Boolean(preview && previewKey === currentPreviewKey);
  const selectedVehicle = vehicles.find((vehicle) => vehicle.id === vehicleId) ?? null;
  const context = useMemo(() => ({ pickupDate, pickupTime: "11:00", dropoffDate, dropoffTime: "11:00" }), [dropoffDate, pickupDate]);
  const pickupLocation = locationForType(locations, pickupTypeKey, "pickup"); const dropoffLocation = locationForType(locations, dropoffTypeKey, "dropoff");

  useEffect(() => { let current = true; void Promise.all([fetchAdminBookingLocations(request), fetchMinimumRentalDays(request)]).then(([items, days]) => { if (!current) return; setLocations(items); setMinimumDays(days); const pickup = locationsForSide(items, "pickup")[0]; const dropoff = locationsForSide(items, "dropoff")[0]; setPickupTypeKey(pickup?.id ?? pickup?.locationTypeKey ?? ""); setDropoffTypeKey(dropoff?.id ?? dropoff?.locationTypeKey ?? ""); }).catch((loadError) => { if (current) setError(loadError instanceof Error ? loadError.message : "Unable to prepare booking controls."); }).finally(() => { if (current) setLoadingSetup(false); }); return () => { current = false; }; }, [request]);
  useEffect(() => { if (!customerId) return; let current = true; void fetchAdminCustomer(request, customerId).then((customer) => { if (!current) return; setCustomerFullName(customer.full_name || ""); setCustomerEmail(customer.email || ""); setCustomerPhone(customer.phone || ""); setCustomerBlocked(Boolean(customer.is_blocked)); }).catch((loadError) => { if (current) setError(loadError instanceof Error ? loadError.message : "Unable to load the selected customer."); }); return () => { current = false; }; }, [customerId, request]);

  const requestBack = useCallback(() => { if (busy) return; if (createdBookingId) { router.replace(`/admin/bookings/${createdBookingId}` as Href); return; } if (!dirty) { router.back(); return; } Alert.alert("Discard this reservation draft?", "No booking has been created yet. The details entered here will be lost.", [{ text: "Keep editing", style: "cancel" }, { text: "Discard", style: "destructive", onPress: () => router.back() }]); }, [busy, createdBookingId, dirty]);
  useFocusEffect(useCallback(() => { const subscription = BackHandler.addEventListener("hardwareBackPress", () => { requestBack(); return true; }); return () => subscription.remove(); }, [requestBack]));
  if (!allowed) return <AdminScreen back title="Workspace unavailable" subtitle="Booking creation requires operations access." />;

  const invalidatePreview = () => { setPreview(null); setPreviewKey(""); };
  const invalidateTrip = () => { setVehicles([]); setVehicleId(""); setInsurance(EMPTY_INSURANCE); setProtectionChoice(""); invalidatePreview(); };
  const changeDates = (nextPickup: string, nextDropoff: string) => { setPickupDate(nextPickup); setDropoffDate(nextDropoff); invalidateTrip(); };
  const checkAvailability = async () => { if (!pickupDate || !dropoffDate) { setError("Choose pickup and return dates first."); return; } setBusy("availability"); setError(""); setWarning(""); invalidateTrip(); try { const items = await fetchAdminAvailableVehicles(request, pickupDate, dropoffDate); setVehicles(items); if (!items.length) setError("No vehicles are currently available for those dates."); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to check availability."); } finally { setBusy(""); } };
  const chooseVehicle = async (vehicle: AdminAvailableVehicle) => { setVehicleId(vehicle.id); setInsurance(EMPTY_INSURANCE); setProtectionChoice(""); invalidatePreview(); setBusy("insurance"); setError(""); try { setInsurance(await fetchAdminInsuranceOption(request, vehicle.id)); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Protection details are unavailable."); } finally { setBusy(""); } };
  const preparePreview = async () => { if (!vehicleId) { setError("Choose an available vehicle first."); return; } if (!protectionChoice) { setError("Choose Standard Protection or No Protection."); return; } if (protectionChoice === "STANDARD" && !insurance.planId) { setError("Standard Protection is not configured for this vehicle."); return; } setBusy("preview"); setError(""); invalidatePreview(); const key = currentPreviewKey; try { const result = await fetchAdminPricingPreview(request, { vehicleId, startDate: pickupDate, endDate: dropoffDate, customerEmail, insuranceSelected: protectionChoice === "STANDARD", insurancePlanId: protectionChoice === "STANDARD" ? insurance.planId : null, promoCode }); setPreview(result); setPreviewKey(key); if (recordPayment && !paymentAmountEdited) setPaymentAmount(String(result.dueNowCents)); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to prepare the booking review."); } finally { setBusy(""); } };
  const matchPickup = () => { if (!pickupLocation) return; const match = locationsForSide(locations, "dropoff").find((location) => location.id === pickupLocation.id) ?? locationsForSide(locations, "dropoff").find((location) => location.locationTypeKey === pickupLocation.locationTypeKey); if (!match) return; setDropoffTypeKey(match.id ?? match.locationTypeKey); setDropoffValues(pickupValues.address ? { address: pickupValues.address } : {}); };
  const bookingInput = () => ({ clientRequestId, customerId, customerFullName, customerEmail, customerPhone, pickupDate, dropoffDate, minimumDays, locations, pickupTypeKey, dropoffTypeKey, pickupValues, dropoffValues, vehicleId, insuranceSelected: protectionChoice === "STANDARD", insurancePlanId: insurance.planId, promoCode });

  const requestCreate = () => { if (customerBlocked) { setError("This customer is blocked. Unblock the profile before creating a booking."); return; } const booking = prepareBookingCreate(bookingInput()); if (!booking.ok) { setError(booking.error); return; } if (!previewCurrent || !preview) { setError("Prepare a fresh live booking review before creating the reservation."); return; } let payment: AdminManualPaymentInput | null = null; if (recordPayment) { const prepared = prepareManualPayment({ amount: paymentAmount, method: paymentMethod, reference: paymentReference, note: paymentNote }); if (!prepared.ok) { setError(prepared.error); return; } payment = prepared.payload; } const paymentEffect = payment ? ` It will then record ${formatJmd(payment.amount)} by ${methodLabel(payment.method)}. A successful payment can establish vehicle entitlement and override competing unpaid reservations.` : " No payment will be recorded or initiated."; Alert.alert("Create and notify?", `This creates a PENDING PAYMENT reservation and sends the customer booking email plus internal notifications.${paymentEffect}`, [{ text: "Review again", style: "cancel" }, { text: payment ? "Create & record payment" : "Create booking", onPress: () => void confirmCreate(booking.payload, payment) }]); };
  const confirmCreate = async (payload: AdminBookingCreateInput, payment: AdminManualPaymentInput | null) => { setBusy("create"); setError(""); setWarning(""); try { const created = await createAdminBooking(request, payload); setCreatedBookingId(created.bookingId); if (!payment) { router.replace(`/admin/bookings/${created.bookingId}` as Href); return; } setBusy("payment"); try { const result = await addAdminBookingPayment(request, created.bookingId, payment); if (result.lost) { setWarning("Booking and payment were recorded, but another paid reservation retained vehicle entitlement. Review this booking before contacting the customer."); setBusy(""); return; } router.replace(`/admin/bookings/${created.bookingId}` as Href); } catch (paymentError) { setWarning(`Booking ${created.bookingId} was created and notifications were sent, but payment was not recorded: ${paymentError instanceof Error ? paymentError.message : "unknown error"}`); setBusy(""); } } catch (createError) { setError(createError instanceof Error ? createError.message : "Unable to create this booking."); setBusy(""); } };

  const selection = buildLocationSelection({ locations, pickupTypeKey, dropoffTypeKey, pickupValues, dropoffValues, context });
  return <AdminScreen back onBackRequest={requestBack} eyebrow="NEW RESERVATION" title="Create booking" subtitle="Review every downstream effect before placing a live reservation.">
    {error ? <Notice error text={error} /> : null}{warning ? <Notice text={warning} /> : null}{customerBlocked ? <Notice error text="This customer is blocked from new bookings." /> : null}
    {createdBookingId ? <AdminCard><SectionTitle number="!" title="Booking created" body="Do not submit this form again. Resolve the payment warning from the booking record." /><Info label="Booking ID" value={createdBookingId} strong /><AdminButton label="Open created booking" onPress={() => router.replace(`/admin/bookings/${createdBookingId}` as Href)} icon="open-in-new" /></AdminCard> : null}
    <AdminCard><SectionTitle number="1" title="Customer and dates" body={`Configured minimum rental: ${minimumDays} ${minimumDays === 1 ? "day" : "days"}. Reservations use the server’s 11:00 Jamaica operational boundary.`} />{customerId ? <View style={styles.linked}><MaterialIcons name="person" size={18} color={colors.tealDark} /><Text style={styles.linkedText}>Creating for an existing customer profile.</Text></View> : null}<Field label="Customer full name *" value={customerFullName} onChangeText={setCustomerFullName} autoCapitalize="words" /><Field label="Email *" value={customerEmail} onChangeText={(value) => { setCustomerEmail(value); invalidatePreview(); }} keyboardType="email-address" autoCapitalize="none" /><Field label="Phone *" value={customerPhone} onChangeText={setCustomerPhone} keyboardType="phone-pad" /><CalendarPicker pickupDate={pickupDate} returnDate={dropoffDate} minimumDays={minimumDays} onChange={changeDates} /></AdminCard>
    <AdminCard><SectionTitle number="2" title="Pickup and return" body="Configured operational fields are attached to the reservation." />{loadingSetup ? <Text style={styles.help}>Loading booking controls…</Text> : <><Text style={styles.label}>PICKUP LOCATION *</Text><View style={styles.chips}>{locationsForSide(locations, "pickup").map((location) => { const selector = location.id ?? location.locationTypeKey; return <Chip key={selector} label={location.pickupLabel} active={pickupTypeKey === selector} onPress={() => { setPickupTypeKey(selector); setPickupValues({}); }} />; })}</View>{locationFields(pickupLocation, "pickup").map((field) => <Field key={`pickup-${field.key}`} label={`${field.label}${field.required ? " *" : ""}`} value={pickupValues[field.key] ?? ""} onChangeText={(value) => setPickupValues((current) => ({ ...current, [field.key]: value }))} placeholder={field.defaultSource ? `Defaults to ${field.defaultSource.replaceAll("_", " ")}` : undefined} keyboardType={field.inputType === "text" ? "default" : "numbers-and-punctuation"} />)}<Pressable onPress={matchPickup} style={styles.match}><MaterialIcons name="content-copy" size={16} color={colors.tealDark} /><Text style={styles.matchText}>Use pickup location for return</Text></Pressable><Text style={styles.label}>RETURN LOCATION *</Text><View style={styles.chips}>{locationsForSide(locations, "dropoff").map((location) => { const selector = location.id ?? location.locationTypeKey; return <Chip key={selector} label={location.dropoffLabel} active={dropoffTypeKey === selector} onPress={() => { setDropoffTypeKey(selector); setDropoffValues({}); }} />; })}</View>{locationFields(dropoffLocation, "dropoff").map((field) => <Field key={`dropoff-${field.key}`} label={`${field.label}${field.required ? " *" : ""}`} value={dropoffValues[field.key] ?? ""} onChangeText={(value) => setDropoffValues((current) => ({ ...current, [field.key]: value }))} placeholder={field.defaultSource ? `Defaults to ${field.defaultSource.replaceAll("_", " ")}` : undefined} keyboardType={field.inputType === "text" ? "default" : "numbers-and-punctuation"} />)}</>}</AdminCard>
    <AdminCard><SectionTitle number="3" title="Availability and pricing" body="The final transaction rechecks availability before committing." /><AdminButton label={busy === "availability" ? "Checking fleet…" : vehicles.length ? "Refresh availability" : "Check live availability"} onPress={() => void checkAvailability()} disabled={Boolean(busy) || loadingSetup} secondary icon="event-available" />{vehicles.map((vehicle) => <Pressable key={vehicle.id} onPress={() => void chooseVehicle(vehicle)} disabled={Boolean(busy)} style={[styles.vehicle, vehicleId === vehicle.id && styles.vehicleSelected]}><View style={[styles.vehicleIcon, vehicleId === vehicle.id && styles.vehicleIconSelected]}><MaterialIcons name={vehicleId === vehicle.id ? "check" : "directions-car"} size={19} color={vehicleId === vehicle.id ? colors.white : colors.tealDark} /></View><View style={styles.vehicleCopy}><Text style={styles.vehicleTitle}>{vehicle.label}</Text><Text style={styles.vehicleMeta}>{formatJmd(vehicle.dailyRateCents)} / day · {formatJmd(vehicle.depositCents)} deposit</Text></View></Pressable>)}{vehicleId && busy === "insurance" ? <Text style={styles.help}>Loading protection option…</Text> : null}{vehicleId && busy !== "insurance" ? <><Text style={styles.label}>PROTECTION CHOICE *</Text><View style={styles.choiceRow}><Choice title="No Protection" value="No additional charge" active={protectionChoice === "NONE"} onPress={() => { setProtectionChoice("NONE"); invalidatePreview(); }} /><Choice title="Standard Protection" value={insurance.enabled ? `${formatJmd(insurance.pricePerDayCents)} / day` : "Not configured"} active={protectionChoice === "STANDARD"} disabled={!insurance.enabled} onPress={() => { setProtectionChoice("STANDARD"); invalidatePreview(); }} /></View><Field label="Promo code" value={promoCode} onChangeText={(value) => { setPromoCode(value.toUpperCase().replace(/\s+/g, "")); invalidatePreview(); }} autoCapitalize="characters" placeholder="Optional" /><AdminButton label={busy === "preview" ? "Preparing review…" : previewCurrent ? "Refresh booking review" : "Prepare booking review"} onPress={() => void preparePreview()} disabled={Boolean(busy) || !protectionChoice} icon="calculate" /></> : null}{previewCurrent && preview ? <View style={styles.pricing}><Info label={`${preview.days} rental ${preview.days === 1 ? "day" : "days"}`} value={formatJmd(preview.baseTotalCents)} /><Info label="Protection" value={formatJmd(preview.insuranceTotalCents)} />{preview.promoDiscountCents > 0 ? <Info label={`Promotion · ${preview.promoCode || promoCode}`} value={`−${formatJmd(preview.promoDiscountCents)}`} good /> : null}<View style={styles.rule} /><Info label="Booking total" value={formatJmd(preview.totalCents)} strong /><Info label="Deposit due" value={formatJmd(preview.dueNowCents)} /><Info label="Balance after deposit" value={formatJmd(preview.balanceDueCents)} /></View> : null}</AdminCard>
    <AdminCard><SectionTitle number="4" title="Payment handling" body="Leave this off to create a pending reservation without collecting money." /><Toggle title="Record an offline payment after creation" body="This is a second transaction and may establish vehicle entitlement." value={recordPayment} onPress={() => { const next = !recordPayment; setRecordPayment(next); if (next && preview && !paymentAmountEdited) setPaymentAmount(String(preview.dueNowCents)); }} />{recordPayment ? <><Field label="Payment amount (JMD) *" value={paymentAmount} onChangeText={(value) => { setPaymentAmount(value.replace(/[^\d.,]/g, "")); setPaymentAmountEdited(true); }} keyboardType="numeric" /><Text style={styles.label}>PAYMENT METHOD *</Text><View style={styles.chips}>{PAYMENT_METHODS.map((method) => <Chip key={method.value} label={method.label} active={paymentMethod === method.value} onPress={() => setPaymentMethod(method.value)} />)}</View><Field label="Reference / receipt number" value={paymentReference} onChangeText={setPaymentReference} placeholder="Strongly recommended" /><Field label="Payment notes" value={paymentNote} onChangeText={setPaymentNote} multiline placeholder="Optional context for the audit trail" /></> : null}</AdminCard>
    <AdminCard><SectionTitle number="5" title="Effects review" body="Preparing this page created nothing. The confirmed action below is the mutation boundary." /><Info label="Customer" value={customerFullName.trim() || "Not entered"} /><Info label="Trip" value={pickupDate && dropoffDate ? `${pickupDate} → ${dropoffDate}` : "Not complete"} /><Info label="Route" value={`${selection.pickupText || "Pickup not set"} → ${selection.dropoffText || "Return not set"}`} /><Info label="Vehicle" value={selectedVehicle?.label || "Not selected"} /><Info label="Total" value={previewCurrent && preview ? formatJmd(preview.totalCents) : "Prepare a fresh review"} strong /><Info label="Initial status" value="Pending payment" /><Info label="Notifications" value="Customer + internal emails" /><Info label="Payment" value={recordPayment ? `${paymentAmount ? formatJmd(Number(paymentAmount.replaceAll(",", ""))) : "Amount required"} · ${methodLabel(paymentMethod)}` : "None recorded"} /><View style={styles.commit}><MaterialIcons name="warning-amber" size={20} color={colors.orangeDark} /><Text style={styles.commitText}>Creating sends notifications. Recording payment can confirm vehicle entitlement and override competing unpaid reservations.</Text></View><AdminButton label={busy === "create" ? "Creating and notifying…" : busy === "payment" ? "Recording payment…" : recordPayment ? "Review create & payment" : "Review and create booking"} onPress={requestCreate} disabled={Boolean(busy) || Boolean(createdBookingId) || !previewCurrent || customerBlocked} icon="event-available" /></AdminCard>
  </AdminScreen>;
}

function Notice({ text, error = false }: { text: string; error?: boolean }) { const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); return <View style={[styles.notice, error && styles.noticeError]}><MaterialIcons name={error ? "error-outline" : "warning-amber"} size={20} color={error ? colors.danger : colors.orangeDark} /><Text style={[styles.noticeText, error && styles.noticeTextError]}>{text}</Text></View>; }
function SectionTitle({ number, title, body }: { number: string; title: string; body: string }) { const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); return <View style={styles.sectionHead}><View style={styles.step}><Text style={styles.stepText}>{number}</Text></View><View style={styles.sectionCopy}><Text style={styles.title}>{title}</Text><Text style={styles.body}>{body}</Text></View></View>; }
function Field({ label, ...props }: { label: string } & React.ComponentProps<typeof TextInput>) { const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); return <View style={styles.field}><Text style={styles.label}>{label.toUpperCase()}</Text><TextInput {...props} placeholderTextColor={colors.muted} style={[styles.input, props.multiline && styles.inputMultiline]} /></View>; }
function Chip({ label, active, disabled, onPress }: { label: string; active: boolean; disabled?: boolean; onPress: () => void }) { const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); return <Pressable disabled={disabled} onPress={onPress} style={[styles.chip, active && styles.chipActive, disabled && styles.disabled]}><Text style={[styles.chipText, active && styles.chipTextActive]}>{label}</Text></Pressable>; }
function Choice({ title, value, active, disabled, onPress }: { title: string; value: string; active: boolean; disabled?: boolean; onPress: () => void }) { const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); return <Pressable disabled={disabled} onPress={onPress} style={[styles.choice, active && styles.choiceActive, disabled && styles.disabled]}><Text style={styles.choiceTitle}>{title}</Text><Text style={styles.choiceValue}>{value}</Text></Pressable>; }
function Toggle({ title, body, value, onPress }: { title: string; body: string; value: boolean; onPress: () => void }) { const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); return <Pressable onPress={onPress} style={styles.toggle}><View style={styles.toggleCopy}><Text style={styles.toggleTitle}>{title}</Text><Text style={styles.toggleBody}>{body}</Text></View><View style={[styles.switchTrack, value && styles.switchTrackOn]}><View style={[styles.switchKnob, value && styles.switchKnobOn]} /></View></Pressable>; }
function Info({ label, value, strong, good }: { label: string; value: string; strong?: boolean; good?: boolean }) { const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); return <View style={styles.info}><Text style={[styles.infoLabel, strong && styles.infoStrong]}>{label}</Text><Text style={[styles.infoValue, strong && styles.infoStrong, good && styles.infoGood]}>{value}</Text></View>; }
function methodLabel(method: AdminManualPaymentMethod) { return PAYMENT_METHODS.find((item) => item.value === method)?.label ?? method; }
function formatJmd(value: number) { return new Intl.NumberFormat("en-JM", { style: "currency", currency: "JMD", maximumFractionDigits: 0 }).format(Math.max(0, Number(value) || 0)); }

const makeStyles = (colors: AppColors) => StyleSheet.create({
  notice: { flexDirection: "row", gap: 8, padding: 13, borderRadius: radii.lg, backgroundColor: colors.cream, borderWidth: 1, borderColor: colors.orange }, noticeError: { backgroundColor: colors.surface, borderColor: colors.danger }, noticeText: { flex: 1, color: colors.orangeDark, fontSize: 11, lineHeight: 17 }, noticeTextError: { color: colors.danger }, linked: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 13, padding: 10, borderRadius: radii.md, backgroundColor: colors.cream }, linkedText: { color: colors.tealDark, fontSize: 10, fontWeight: "800" },
  sectionHead: { flexDirection: "row", alignItems: "flex-start", gap: 11 }, step: { width: 32, height: 32, borderRadius: 12, backgroundColor: colors.navy, alignItems: "center", justifyContent: "center" }, stepText: { color: colors.white, fontSize: 12, fontWeight: "900" }, sectionCopy: { flex: 1 }, title: { color: colors.text, fontSize: 19, fontWeight: "900" }, body: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 4 },
  field: { marginTop: 13 }, label: { color: colors.muted, fontSize: 8, fontWeight: "900", letterSpacing: 0.6, marginTop: 12, marginBottom: 7 }, input: { minHeight: 49, paddingHorizontal: 13, borderRadius: radii.md, backgroundColor: colors.surfaceSoft, borderWidth: 1, borderColor: colors.border, color: colors.text, fontSize: 13 }, inputMultiline: { minHeight: 84, paddingTop: 13, textAlignVertical: "top" }, help: { color: colors.muted, fontSize: 9, lineHeight: 14, marginTop: 9 },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, chip: { minHeight: 39, paddingHorizontal: 12, alignItems: "center", justifyContent: "center", borderRadius: radii.pill, borderWidth: 1, borderColor: colors.border }, chipActive: { backgroundColor: colors.teal, borderColor: colors.teal }, chipText: { color: colors.muted, fontSize: 9, fontWeight: "900" }, chipTextActive: { color: colors.white }, disabled: { opacity: 0.45 }, match: { flexDirection: "row", alignItems: "center", gap: 6, alignSelf: "flex-start", marginTop: 15, paddingVertical: 8 }, matchText: { color: colors.tealDark, fontSize: 10, fontWeight: "900" },
  vehicle: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 10, padding: 11, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md }, vehicleSelected: { borderColor: colors.teal, backgroundColor: colors.cream }, vehicleIcon: { width: 39, height: 39, borderRadius: 13, backgroundColor: colors.surfaceSoft, alignItems: "center", justifyContent: "center" }, vehicleIconSelected: { backgroundColor: colors.teal }, vehicleCopy: { flex: 1 }, vehicleTitle: { color: colors.text, fontSize: 12, fontWeight: "900" }, vehicleMeta: { color: colors.muted, fontSize: 9, marginTop: 3 }, choiceRow: { flexDirection: "row", gap: 9 }, choice: { flex: 1, minHeight: 84, padding: 12, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md, backgroundColor: colors.surface }, choiceActive: { borderColor: colors.teal, backgroundColor: colors.cream }, choiceTitle: { color: colors.text, fontSize: 11, fontWeight: "900" }, choiceValue: { color: colors.muted, fontSize: 9, lineHeight: 14, marginTop: 8 },
  pricing: { marginTop: 14, padding: 13, borderRadius: radii.md, backgroundColor: colors.surfaceSoft }, rule: { height: 1, backgroundColor: colors.border, marginVertical: 7 }, toggle: { flexDirection: "row", alignItems: "center", gap: 12, marginTop: 15, padding: 12, borderRadius: radii.md, backgroundColor: colors.surfaceSoft }, toggleCopy: { flex: 1 }, toggleTitle: { color: colors.text, fontSize: 12, fontWeight: "900" }, toggleBody: { color: colors.muted, fontSize: 9, lineHeight: 14, marginTop: 3 }, switchTrack: { width: 44, height: 26, padding: 3, borderRadius: 13, backgroundColor: colors.border }, switchTrackOn: { backgroundColor: colors.teal }, switchKnob: { width: 20, height: 20, borderRadius: 10, backgroundColor: colors.white }, switchKnobOn: { marginLeft: 18 },
  info: { flexDirection: "row", justifyContent: "space-between", gap: 12, paddingVertical: 7 }, infoLabel: { flex: 1, color: colors.muted, fontSize: 11 }, infoValue: { flex: 1, color: colors.text, fontSize: 11, fontWeight: "900", textAlign: "right" }, infoStrong: { color: colors.text, fontSize: 13, fontWeight: "900" }, infoGood: { color: colors.success }, commit: { flexDirection: "row", gap: 8, padding: 12, marginTop: 10, borderRadius: radii.md, backgroundColor: colors.cream }, commitText: { flex: 1, color: colors.orangeDark, fontSize: 10, lineHeight: 15, fontWeight: "800" },
});
