import { MaterialIcons } from "@expo/vector-icons";
import { router, type Href, useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, Linking, Pressable, StyleSheet, Text, View } from "react-native";
import { useAdminAuth } from "@/admin/AdminAuthProvider"; import { fetchAdminMessage, updateAdminMessage, type AdminMessageAction, type AdminMessageDetail } from "@/admin/api"; import { hasCapability } from "@/admin/capabilities"; import { AdminButton, AdminCard, AdminGate, AdminScreen } from "@/admin/AdminShell"; import { useAppTheme } from "@/components/ThemeProvider"; import { radii, type AppColors } from "@/constants/theme";
export default function MessageDetailScreen() { return <AdminGate><MessageDetail /></AdminGate>; }
function MessageDetail() { const { id } = useLocalSearchParams<{ id?: string }>(); const { request, user } = useAdminAuth(); const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); const allowed = Boolean(user && hasCapability(user.role, "messages.read")); const [item, setItem] = useState<AdminMessageDetail | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { if (!id || !allowed) return; setLoading(true); setError(""); try { setItem(await fetchAdminMessage(request, id, true)); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load this message."); } finally { setLoading(false); } }, [allowed, id, request]); useEffect(() => { const task = setTimeout(() => void load(), 0); return () => clearTimeout(task); }, [load]);
  const act = (action: AdminMessageAction) => { const destructive = action === "DELETE_PERMANENT"; const archive = action === "ARCHIVE"; if (destructive || archive) { Alert.alert(destructive ? "Delete message permanently?" : "Move message to trash?", destructive ? "This cannot be undone. Audit metadata remains, but the message body will be removed." : "You can restore this message from Trash later.", [{ text: "Not now", style: "cancel" }, { text: destructive ? "Delete permanently" : "Move to trash", style: destructive ? "destructive" : "default", onPress: () => void perform(action) }]); return; } void perform(action); };
  const perform = async (action: AdminMessageAction) => { if (!id) return; setBusy(action); setError(""); setNotice(""); try { const result = await updateAdminMessage(request, id, action); if (result.deleted) { router.replace("/admin/messages" as Href); return; } setItem(result.item); setNotice(action === "MARK_NEW" ? "Message returned to New." : action === "UNARCHIVE" ? "Message restored to the inbox." : "Message updated."); } catch (actionError) { setError(actionError instanceof Error ? actionError.message : "Unable to update this message."); } finally { setBusy(""); } };
  const openRelated = () => { if (!item?.relatedEntityId || !item.relatedEntityType) return; if (item.relatedEntityType === "booking") router.push(`/admin/bookings/${item.relatedEntityId}` as Href); else if (item.relatedEntityType === "quote") router.push(`/admin/quotes/${item.relatedEntityId}` as Href); else if (item.relatedEntityType === "contact_message") router.push(`/admin/messages/${item.relatedEntityId}` as Href); };
  if (!allowed) return <AdminScreen back title="Workspace unavailable" subtitle="Message triage requires an administrator role." />;
  return <AdminScreen back eyebrow={item?.sourceLabel || "MESSAGE"} title={item?.subject || "Message detail"} subtitle={item ? `From ${item.displayName || item.name} · ${formatTimestamp(item.createdAt)}` : "Loading message…"} refreshing={loading && Boolean(item)} onRefresh={() => void load()}>{error ? <View style={styles.error}><MaterialIcons name="error-outline" size={20} color={colors.danger} /><Text style={styles.errorText}>{error}</Text><Pressable onPress={() => void load()}><Text style={styles.retry}>Retry</Text></Pressable></View> : null}{notice ? <View style={styles.notice}><MaterialIcons name="check-circle" size={20} color={colors.success} /><Text style={styles.noticeText}>{notice}</Text></View> : null}{item ? <>
    <AdminCard><View style={styles.sender}><View style={styles.avatar}><Text style={styles.avatarText}>{initials(item.displayName || item.name)}</Text></View><View style={styles.senderCopy}><Text style={styles.senderName}>{item.displayName || item.name}</Text><Text style={styles.senderEmail}>{item.displayEmail || item.email}</Text></View><View style={styles.status}><Text style={styles.statusText}>{item.statusLabel}</Text></View></View><View style={styles.divider} /><Text style={styles.message}>{item.message}</Text></AdminCard>
    <AdminCard><Text style={styles.sectionTitle}>Contact customer</Text><Text style={styles.sectionBody}>This opens your device’s mail app; replies are not automatically copied into this inbox.</Text><AdminButton label="Write email" onPress={() => void Linking.openURL(`mailto:${encodeURIComponent(item.displayEmail || item.email)}?subject=${encodeURIComponent(`Re: ${item.subject || "Your Curated Car Rentals enquiry"}`)}`)} secondary icon="mail" /></AdminCard>
    {item.relatedEntityId && ["booking", "quote", "contact_message"].includes(item.relatedEntityType || "") ? <AdminCard><Text style={styles.sectionTitle}>Related record</Text><Text style={styles.sectionBody}>{item.relatedEntityLabel || "Open the linked staff record for more context."}</Text><AdminButton label={`Open ${item.relatedEntityType}`} onPress={openRelated} secondary icon="open-in-new" /></AdminCard> : null}
    <AdminCard><Text style={styles.sectionTitle}>Inbox actions</Text>{item.status === "READ" ? <AdminButton label={busy === "MARK_NEW" ? "Updating…" : "Mark as new"} onPress={() => act("MARK_NEW")} disabled={Boolean(busy)} secondary icon="mark-email-unread" /> : null}{item.status !== "ARCHIVED" ? <AdminButton label={busy === "ARCHIVE" ? "Moving to trash…" : "Move to trash"} onPress={() => act("ARCHIVE")} disabled={Boolean(busy)} secondary icon="delete-outline" /> : <><AdminButton label={busy === "UNARCHIVE" ? "Restoring…" : "Restore to inbox"} onPress={() => act("UNARCHIVE")} disabled={Boolean(busy)} secondary icon="restore" /><AdminButton label={busy === "DELETE_PERMANENT" ? "Deleting…" : "Delete permanently"} onPress={() => act("DELETE_PERMANENT")} disabled={Boolean(busy)} secondary icon="delete-forever" /></>}</AdminCard>
  </> : null}</AdminScreen>;
}
function initials(name: string) { return name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]?.toUpperCase()).join("") || "?"; } function formatTimestamp(value: string) { const d = new Date(value); return Number.isNaN(d.getTime()) ? value : new Intl.DateTimeFormat("en-JM", { dateStyle: "medium", timeStyle: "short" }).format(d); }
const makeStyles = (colors: AppColors) => StyleSheet.create({ error: { flexDirection: "row", gap: 8, padding: 13, borderRadius: radii.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.danger }, errorText: { flex: 1, color: colors.danger, fontSize: 12 }, retry: { color: colors.tealDark, fontSize: 11, fontWeight: "900" }, notice: { flexDirection: "row", gap: 8, padding: 13, borderRadius: radii.lg, backgroundColor: colors.cream }, noticeText: { flex: 1, color: colors.success, fontSize: 12, fontWeight: "800" }, sender: { flexDirection: "row", alignItems: "center", gap: 11 }, avatar: { width: 48, height: 48, borderRadius: 17, alignItems: "center", justifyContent: "center", backgroundColor: colors.cream }, avatarText: { color: colors.tealDark, fontSize: 14, fontWeight: "900" }, senderCopy: { flex: 1 }, senderName: { color: colors.text, fontSize: 15, fontWeight: "900" }, senderEmail: { color: colors.muted, fontSize: 10, marginTop: 4 }, status: { paddingHorizontal: 9, paddingVertical: 5, borderRadius: radii.pill, backgroundColor: colors.surfaceSoft }, statusText: { color: colors.tealDark, fontSize: 8, fontWeight: "900" }, divider: { height: 1, backgroundColor: colors.border, marginVertical: 17 }, message: { color: colors.text, fontSize: 14, lineHeight: 23 }, sectionTitle: { color: colors.text, fontSize: 19, fontWeight: "900" }, sectionBody: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 6 }, });
