import { MaterialIcons } from "@expo/vector-icons";
import { router, type Href } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { useAdminAuth } from "@/admin/AdminAuthProvider";
import { fetchAdminEmails, type AdminEmailListItem } from "@/admin/api";
import { hasCapability } from "@/admin/capabilities";
import { AdminButton, AdminGate, AdminScreen } from "@/admin/AdminShell";
import { useAppTheme } from "@/components/ThemeProvider";
import { radii, type AppColors } from "@/constants/theme";

const STATUS_FILTERS = [{ key: "all", label: "All" }, { key: "DELIVERED", label: "Delivered" }, { key: "SENT", label: "Accepted" }, { key: "FAILED", label: "Failed" }, { key: "BOUNCED", label: "Bounced" }, { key: "DELIVERY_ISSUE", label: "Issue" }] as const;

export default function AdminEmailsScreen() { return <AdminGate><EmailWorkspace /></AdminGate>; }

function EmailWorkspace() {
  const { request, user } = useAdminAuth(); const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]);
  const allowed = Boolean(user && hasCapability(user.role, "emails.read"));
  const [queryInput, setQueryInput] = useState(""); const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [page, setPage] = useState(1);
  const [advanced, setAdvanced] = useState(false); const [emailTypeInput, setEmailTypeInput] = useState(""); const [entityTypeInput, setEntityTypeInput] = useState(""); const [triggerInput, setTriggerInput] = useState(""); const [fromInput, setFromInput] = useState(""); const [toInput, setToInput] = useState("");
  const [filters, setFilters] = useState({ emailType: "", entityType: "", triggerSource: "", dateFrom: "", dateTo: "" });
  const [data, setData] = useState<Awaited<ReturnType<typeof fetchAdminEmails>> | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { if (!allowed) return; setLoading(true); setError(""); try { setData(await fetchAdminEmails(request, { q: query, status, page, limit: 20, ...filters })); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load email activity."); } finally { setLoading(false); } }, [allowed, filters, page, query, request, status]);
  useEffect(() => { const task = setTimeout(() => void load(), 0); return () => clearTimeout(task); }, [load]);
  if (!allowed) return <AdminScreen back title="Workspace unavailable" subtitle="Email delivery activity requires administrator access." />;
  const applySearch = () => { setPage(1); setQuery(queryInput.trim()); };
  const applyAdvanced = () => { const from = fromInput.trim(); const to = toInput.trim(); if ((from && !validDateOnly(from)) || (to && !validDateOnly(to))) { setError("Use valid From and To dates in YYYY-MM-DD format."); return; } if (from && to && from > to) { setError("The To date must be on or after the From date."); return; } setError(""); setPage(1); setFilters({ emailType: emailTypeInput.trim(), entityType: entityTypeInput.trim(), triggerSource: triggerInput.trim(), dateFrom: from, dateTo: to }); };
  const clear = () => { setQueryInput(""); setQuery(""); setStatus("all"); setEmailTypeInput(""); setEntityTypeInput(""); setTriggerInput(""); setFromInput(""); setToInput(""); setFilters({ emailType: "", entityType: "", triggerSource: "", dateFrom: "", dateTo: "" }); setPage(1); };
  const activeFilters = Boolean(query || status !== "all" || Object.values(filters).some(Boolean));
  return <AdminScreen back eyebrow="DELIVERY MONITORING" title="Email activity" subtitle="Trace customer communications, find delivery failures, and safely repeat supported messages." refreshing={loading && Boolean(data)} onRefresh={() => void load()}>
    <View style={styles.metrics}><Metric label="TOTAL" value={String(data?.summary.total ?? 0)} /><Metric label="FAILED" value={String(data?.summary.failed ?? 0)} tone="danger" /><Metric label="BOUNCED / ISSUE" value={String(data?.summary.bouncedOrIssue ?? 0)} tone="warn" /><Metric label="PENDING / UNKNOWN" value={String(data?.summary.pendingOrUnknown ?? 0)} /></View>
    <View style={styles.searchRow}><View style={styles.search}><MaterialIcons name="search" size={20} color={colors.muted} /><TextInput value={queryInput} onChangeText={setQueryInput} onSubmitEditing={applySearch} placeholder="Recipient, subject, reference, provider ID" placeholderTextColor={colors.muted} autoCapitalize="none" style={styles.searchInput} returnKeyType="search" /></View><Pressable onPress={applySearch} style={styles.searchButton}><MaterialIcons name="arrow-forward" size={21} color={colors.white} /></Pressable></View>
    <View style={styles.filters}>{STATUS_FILTERS.map((item) => <Pressable key={item.key} onPress={() => { setPage(1); setStatus(item.key); }} style={[styles.filter, status === item.key && styles.filterActive]}><Text style={[styles.filterText, status === item.key && styles.filterTextActive]}>{item.label}</Text></Pressable>)}</View>
    <Pressable onPress={() => setAdvanced((current) => !current)} style={styles.advancedButton}><MaterialIcons name="tune" size={18} color={colors.tealDark} /><Text style={styles.advancedText}>Type, source, and date filters</Text><MaterialIcons name={advanced ? "expand-less" : "expand-more"} size={20} color={colors.muted} /></Pressable>
    {advanced ? <View style={styles.advanced}><Field label="Email type" value={emailTypeInput} onChangeText={setEmailTypeInput} placeholder="booking_created" /><Field label="Entity type" value={entityTypeInput} onChangeText={setEntityTypeInput} placeholder="booking" /><Field label="Trigger source" value={triggerInput} onChangeText={setTriggerInput} placeholder="admin_resend" /><View style={styles.two}><View style={styles.half}><Field label="From" value={fromInput} onChangeText={setFromInput} placeholder="YYYY-MM-DD" /></View><View style={styles.half}><Field label="To" value={toInput} onChangeText={setToInput} placeholder="YYYY-MM-DD" /></View></View><AdminButton label="Apply advanced filters" secondary onPress={applyAdvanced} /></View> : null}
    <View style={styles.result}><View><Text style={styles.resultTitle}>{loading && !data ? "Loading delivery history…" : `${data?.totalCount ?? 0} ${(data?.totalCount ?? 0) === 1 ? "email" : "emails"}`}</Text>{data && data.totalCount > 0 ? <Text style={styles.resultMeta}>Showing {data.from}–{data.to} · Page {data.page} of {data.totalPages}</Text> : null}</View>{activeFilters ? <Pressable onPress={clear}><Text style={styles.clear}>Clear filters</Text></Pressable> : null}</View>
    {error ? <View style={styles.error}><MaterialIcons name="error-outline" size={20} color={colors.danger} /><Text style={styles.errorText}>{error}</Text><Pressable onPress={() => void load()}><Text style={styles.retry}>Retry</Text></Pressable></View> : null}
    {!loading && !error && !data?.items.length ? <View style={styles.empty}><View style={styles.emptyIcon}><MaterialIcons name="mark-email-read" size={28} color={colors.orange} /></View><Text style={styles.emptyTitle}>No email activity matches</Text><Text style={styles.emptyBody}>Adjust the delivery filters or clear them to review the full communication history.</Text></View> : null}
    <View style={styles.list}>{data?.items.map((item) => <EmailCard key={item.id} item={item} />)}</View>
    {data && (data.hasPrev || data.hasNext) ? <View style={styles.pager}><View style={styles.pagerButton}><AdminButton label="Previous" secondary disabled={!data.hasPrev || loading} onPress={() => setPage((current) => Math.max(1, current - 1))} /></View><Text style={styles.pageLabel}>{data.page} / {data.totalPages}</Text><View style={styles.pagerButton}><AdminButton label="Next" secondary disabled={!data.hasNext || loading} onPress={() => setPage((current) => current + 1)} /></View></View> : null}
  </AdminScreen>;
}

function EmailCard({ item }: { item: AdminEmailListItem }) { const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); const tone = statusTone(item.status); return <Pressable onPress={() => router.push(`/admin/emails/${encodeURIComponent(item.id)}` as Href)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.cardTop}><View style={[styles.statusIcon, tone === "good" && styles.statusGood, tone === "danger" && styles.statusDanger, tone === "warn" && styles.statusWarn]}><MaterialIcons name={tone === "good" ? "done-all" : tone === "danger" ? "error-outline" : tone === "warn" ? "warning-amber" : "schedule"} size={20} color={tone === "good" ? colors.success : tone === "danger" ? colors.danger : tone === "warn" ? colors.orangeDark : colors.muted} /></View><View style={styles.cardCopy}><View style={styles.badgeRow}><Text style={styles.type}>{label(item.emailType)}</Text><Text style={[styles.status, tone === "good" && styles.statusTextGood, tone === "danger" && styles.statusTextDanger, tone === "warn" && styles.statusTextWarn]}>{item.status === "SENT" ? "Accepted" : label(item.status)}</Text></View><Text style={styles.subject} numberOfLines={2}>{item.subject || label(item.emailType)}</Text><Text style={styles.recipient}>{item.recipientName || "Recipient"} · {item.recipientEmail || "Legacy recipient unavailable"}</Text></View></View><View style={styles.meta}><MaterialIcons name="schedule" size={15} color={colors.muted} /><Text style={styles.metaText}>{timestamp(item.lastEventAt || item.sentAt || item.createdAt)}</Text></View><View style={styles.meta}><MaterialIcons name="link" size={15} color={colors.muted} /><Text style={styles.metaText}>{item.entityPublicId || item.entityId || label(item.entityType)}</Text></View>{item.lastError ? <View style={styles.failure}><Text style={styles.failureText} numberOfLines={2}>{item.lastError}</Text></View> : null}<View style={styles.open}><Text style={styles.openText}>{item.manualResendAllowed ? "Inspect and resend" : "Inspect delivery"}</Text><MaterialIcons name="chevron-right" size={21} color={colors.orange} /></View></Pressable>; }
function Metric({ label: text, value, tone }: { label: string; value: string; tone?: "danger" | "warn" }) { const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); return <View style={styles.metric}><Text style={[styles.metricValue, tone === "danger" && { color: colors.danger }, tone === "warn" && { color: colors.orangeDark }]}>{value}</Text><Text style={styles.metricLabel}>{text}</Text></View>; }
function Field({ label: text, ...props }: { label: string } & React.ComponentProps<typeof TextInput>) { const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); return <View style={styles.field}><Text style={styles.fieldLabel}>{text.toUpperCase()}</Text><TextInput {...props} autoCapitalize="none" placeholderTextColor={colors.muted} style={styles.input} /></View>; }
function statusTone(value: string) { const status = value.toUpperCase(); if (status === "DELIVERED") return "good"; if (status === "FAILED") return "danger"; if (status === "BOUNCED" || status === "DELIVERY_ISSUE") return "warn"; return "neutral"; }
function validDateOnly(value: string) { if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false; const date = new Date(`${value}T12:00:00Z`); return !Number.isNaN(date.getTime()) && date.toISOString().slice(0, 10) === value; }
function label(value: string | null) { const text = String(value || "—").replace(/[_.]+/g, " ").toLowerCase(); return text.replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function timestamp(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-JM", { dateStyle: "medium", timeStyle: "short" }).format(date); }

const makeStyles = (colors: AppColors) => StyleSheet.create({
  metrics: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, metric: { width: "48%", minHeight: 75, padding: 12, borderRadius: radii.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, metricValue: { color: colors.tealDark, fontSize: 23, fontWeight: "900" }, metricLabel: { color: colors.muted, fontSize: 8, fontWeight: "900", marginTop: 4 }, searchRow: { flexDirection: "row", gap: 9 }, search: { flex: 1, minHeight: 50, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", gap: 8, borderRadius: radii.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, searchInput: { flex: 1, color: colors.text, fontSize: 12 }, searchButton: { width: 50, height: 50, borderRadius: radii.md, alignItems: "center", justifyContent: "center", backgroundColor: colors.orange }, filters: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, filter: { paddingHorizontal: 11, paddingVertical: 8, borderRadius: radii.pill, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, filterActive: { backgroundColor: colors.teal, borderColor: colors.teal }, filterText: { color: colors.muted, fontSize: 9, fontWeight: "900" }, filterTextActive: { color: colors.white }, advancedButton: { minHeight: 47, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", gap: 8, borderRadius: radii.lg, backgroundColor: colors.cream }, advancedText: { flex: 1, color: colors.tealDark, fontSize: 10, fontWeight: "900" }, advanced: { padding: 13, borderRadius: radii.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, field: { marginTop: 10 }, fieldLabel: { color: colors.muted, fontSize: 8, fontWeight: "900", marginBottom: 6 }, input: { minHeight: 46, paddingHorizontal: 12, borderRadius: radii.md, color: colors.text, backgroundColor: colors.surfaceSoft, borderWidth: 1, borderColor: colors.border, fontSize: 12 }, two: { flexDirection: "row", gap: 9 }, half: { flex: 1 }, result: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 10 }, resultTitle: { color: colors.text, fontSize: 17, fontWeight: "900" }, resultMeta: { color: colors.muted, fontSize: 9, marginTop: 3 }, clear: { color: colors.tealDark, fontSize: 10, fontWeight: "900" },
  error: { flexDirection: "row", alignItems: "center", gap: 8, padding: 13, borderRadius: radii.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.danger }, errorText: { flex: 1, color: colors.danger, fontSize: 11 }, retry: { color: colors.tealDark, fontSize: 10, fontWeight: "900" }, empty: { alignItems: "center", padding: 27, borderRadius: radii.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, emptyIcon: { width: 56, height: 56, borderRadius: 19, alignItems: "center", justifyContent: "center", backgroundColor: colors.cream }, emptyTitle: { color: colors.text, fontSize: 18, fontWeight: "900", marginTop: 12 }, emptyBody: { color: colors.muted, fontSize: 11, lineHeight: 17, textAlign: "center", marginTop: 5 }, list: { gap: 9 }, card: { padding: 15, borderRadius: radii.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, pressed: { opacity: 0.65 }, cardTop: { flexDirection: "row", gap: 10 }, statusIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: colors.surfaceSoft }, statusGood: { backgroundColor: colors.cream }, statusDanger: { backgroundColor: colors.surfaceSoft }, statusWarn: { backgroundColor: colors.surfaceSoft }, cardCopy: { flex: 1 }, badgeRow: { flexDirection: "row", justifyContent: "space-between", gap: 8 }, type: { flex: 1, color: colors.orange, fontSize: 8, fontWeight: "900", letterSpacing: 0.4 }, status: { color: colors.muted, fontSize: 8, fontWeight: "900" }, statusTextGood: { color: colors.success }, statusTextDanger: { color: colors.danger }, statusTextWarn: { color: colors.orangeDark }, subject: { color: colors.text, fontSize: 14, lineHeight: 19, fontWeight: "900", marginTop: 6 }, recipient: { color: colors.muted, fontSize: 9, marginTop: 4 }, meta: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 9 }, metaText: { flex: 1, color: colors.muted, fontSize: 9 }, failure: { marginTop: 9, padding: 9, borderRadius: radii.md, backgroundColor: colors.surfaceSoft }, failureText: { color: colors.danger, fontSize: 9, lineHeight: 14 }, open: { flexDirection: "row", justifyContent: "flex-end", alignItems: "center", marginTop: 11, paddingTop: 9, borderTopWidth: 1, borderTopColor: colors.border }, openText: { color: colors.tealDark, fontSize: 10, fontWeight: "900" }, pager: { flexDirection: "row", alignItems: "center", gap: 9 }, pagerButton: { flex: 1 }, pageLabel: { color: colors.muted, fontSize: 9, fontWeight: "900" },
});
