export const REMINDER_EVENTS = {
  PICKUP_SENT: "BOOKING_PICKUP_REMINDER_SENT",
  PICKUP_FAILED: "BOOKING_PICKUP_REMINDER_FAILED",
  BALANCE_SENT: "BOOKING_BALANCE_REMINDER_SENT",
  BALANCE_FAILED: "BOOKING_BALANCE_REMINDER_FAILED",
  DROPOFF_SENT: "BOOKING_DROPOFF_REMINDER_SENT",
  DROPOFF_FAILED: "BOOKING_DROPOFF_REMINDER_FAILED",
  LATE_DROPOFF_SENT: "BOOKING_LATE_DROPOFF_ALERT_SENT",
  LATE_DROPOFF_FAILED: "BOOKING_LATE_DROPOFF_ALERT_FAILED",
  NOTE_SENT: "BOOKING_NOTE_EMAIL_SENT",
  NOTE_FAILED: "BOOKING_NOTE_EMAIL_FAILED",
  NOTE_CANCELLED: "BOOKING_NOTE_EMAIL_CANCELLED",
} as const;

export type ReminderEventType = (typeof REMINDER_EVENTS)[keyof typeof REMINDER_EVENTS];

export const REMINDER_EVENT_TYPES = Object.values(REMINDER_EVENTS) as ReminderEventType[];

export type ReminderRunStatus = "SUCCESS" | "FAILED" | "CANCELLED";

export const REMINDER_EVENT_LABELS: Record<ReminderEventType, string> = {
  [REMINDER_EVENTS.PICKUP_SENT]: "Pickup reminder sent",
  [REMINDER_EVENTS.PICKUP_FAILED]: "Pickup reminder failed",
  [REMINDER_EVENTS.BALANCE_SENT]: "Balance reminder sent",
  [REMINDER_EVENTS.BALANCE_FAILED]: "Balance reminder failed",
  [REMINDER_EVENTS.DROPOFF_SENT]: "Dropoff reminder sent",
  [REMINDER_EVENTS.DROPOFF_FAILED]: "Dropoff reminder failed",
  [REMINDER_EVENTS.LATE_DROPOFF_SENT]: "Late dropoff alert sent",
  [REMINDER_EVENTS.LATE_DROPOFF_FAILED]: "Late dropoff alert failed",
  [REMINDER_EVENTS.NOTE_SENT]: "Scheduled note email sent",
  [REMINDER_EVENTS.NOTE_FAILED]: "Scheduled note email failed",
  [REMINDER_EVENTS.NOTE_CANCELLED]: "Scheduled note email cancelled",
};

export const CRON_RUN_AUDIT_ACTION = "CRON_REMINDER_RUN";

export const PICKUP_REMINDER_EVENT_TYPES: ReminderEventType[] = [
  REMINDER_EVENTS.PICKUP_SENT,
  REMINDER_EVENTS.PICKUP_FAILED,
];

export const BALANCE_REMINDER_EVENT_TYPES: ReminderEventType[] = [
  REMINDER_EVENTS.BALANCE_SENT,
  REMINDER_EVENTS.BALANCE_FAILED,
  REMINDER_EVENTS.DROPOFF_SENT,
  REMINDER_EVENTS.DROPOFF_FAILED,
  REMINDER_EVENTS.LATE_DROPOFF_SENT,
  REMINDER_EVENTS.LATE_DROPOFF_FAILED,
];

export const NOTE_REMINDER_EVENT_TYPES: ReminderEventType[] = [
  REMINDER_EVENTS.NOTE_SENT,
  REMINDER_EVENTS.NOTE_FAILED,
  REMINDER_EVENTS.NOTE_CANCELLED,
];

const REMINDER_EVENT_TYPE_SET = new Set<string>(REMINDER_EVENT_TYPES);

export function isReminderEventType(value: unknown): value is ReminderEventType {
  return typeof value === "string" && REMINDER_EVENT_TYPE_SET.has(value);
}
