import { MaterialIcons } from "@expo/vector-icons";
import { router, type Href } from "expo-router";
import { useMemo, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useAdminAuth } from "@/admin/AdminAuthProvider"; import { createAdminUser } from "@/admin/api"; import { hasCapability } from "@/admin/capabilities"; import { AdminButton, AdminCard, AdminGate, AdminScreen } from "@/admin/AdminShell"; import { useAppTheme } from "@/components/ThemeProvider"; import { radii, type AppColors } from "@/constants/theme";
export default function NewUserScreen() { return <AdminGate><NewUser /></AdminGate>; }
function NewUser() { const { request, user } = useAdminAuth(); const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); const allowed = Boolean(user && hasCapability(user.role, "users.write")); const roles = user?.role === "DEVELOPER" ? ["OPERATIONS", "ADMIN", "DEVELOPER"] : ["OPERATIONS", "ADMIN"]; const [firstName, setFirstName] = useState(""); const [lastName, setLastName] = useState(""); const [email, setEmail] = useState(""); const [role, setRole] = useState("OPERATIONS"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const save = async () => { if (!firstName.trim() || !lastName.trim() || !email.includes("@")) { setError("Enter the staff member’s first name, last name, and valid email."); return; } setBusy(true); setError(""); try { const result = await createAdminUser(request, { firstName: firstName.trim(), lastName: lastName.trim(), email: email.trim().toLowerCase(), role }); Alert.alert("Setup pending", result.welcomeEmail?.warning || `A setup invitation was sent to ${result.setupEmail}. The account remains disabled until setup is completed.`, [{ text: "View user", onPress: () => router.replace(`/admin/users/${result.userId}` as Href) }]); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Unable to create staff user."); } finally { setBusy(false); } };
  if (!allowed) return <AdminScreen back title="Workspace unavailable" subtitle="User onboarding requires administrator access." />;
  return <AdminScreen back eyebrow="STAFF ONBOARDING" title="Add staff user" subtitle="Create a setup-pending account and assign only the access this person needs.">{error ? <View style={styles.error}><MaterialIcons name="error-outline" size={20} color={colors.danger} /><Text style={styles.errorText}>{error}</Text></View> : null}<AdminCard><Text style={styles.title}>Staff identity</Text><Field label="First name *" value={firstName} onChangeText={setFirstName} autoCapitalize="words" /><Field label="Last name *" value={lastName} onChangeText={setLastName} autoCapitalize="words" /><Field label="Work email *" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" /><Text style={styles.fieldLabel}>Initial role</Text><View style={styles.roles}>{roles.map((item) => <Pressable key={item} onPress={() => setRole(item)} style={[styles.role, role === item && styles.roleActive]}><Text style={[styles.roleText, role === item && styles.roleTextActive]}>{item}</Text><Text style={[styles.roleDescription, role === item && styles.roleTextActive]}>{item === "OPERATIONS" ? "Bookings, quotes, customers" : item === "ADMIN" ? "Business and system administration" : "Developer-level administration"}</Text></Pressable>)}</View><View style={styles.notice}><MaterialIcons name="outgoing-mail" size={19} color={colors.tealDark} /><Text style={styles.noticeText}>The account cannot sign in until the recipient completes the dedicated setup flow.</Text></View><AdminButton label={busy ? "Creating setup account…" : "Create and send setup invite"} onPress={() => void save()} disabled={busy} icon="person-add" /></AdminCard></AdminScreen>;
}
function Field({ label, ...props }: { label: string } & React.ComponentProps<typeof TextInput>) { const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><TextInput {...props} placeholderTextColor={colors.muted} style={styles.input} /></View>; }
const makeStyles = (colors: AppColors) => StyleSheet.create({ title: { color: colors.text, fontSize: 20, fontWeight: "900" }, field: { marginTop: 14 }, fieldLabel: { color: colors.muted, fontSize: 10, fontWeight: "900", marginTop: 14, marginBottom: 7 }, input: { minHeight: 50, paddingHorizontal: 14, borderRadius: radii.md, backgroundColor: colors.surfaceSoft, borderWidth: 1, borderColor: colors.border, color: colors.text }, roles: { gap: 8 }, role: { padding: 13, borderRadius: radii.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, roleActive: { backgroundColor: colors.teal, borderColor: colors.teal }, roleText: { color: colors.text, fontSize: 12, fontWeight: "900" }, roleTextActive: { color: colors.white }, roleDescription: { color: colors.muted, fontSize: 9, marginTop: 4 }, notice: { flexDirection: "row", gap: 8, padding: 12, borderRadius: radii.md, backgroundColor: colors.cream, marginTop: 16 }, noticeText: { flex: 1, color: colors.tealDark, fontSize: 11, lineHeight: 17, fontWeight: "700" }, error: { flexDirection: "row", gap: 8, padding: 13, borderRadius: radii.lg, borderWidth: 1, borderColor: colors.danger, backgroundColor: colors.surface }, errorText: { flex: 1, color: colors.danger, fontSize: 12 }, });
