import { MaterialIcons } from "@expo/vector-icons";
import { router, type Href, useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";

import { useAdminAuth } from "@/admin/AdminAuthProvider";
import { fetchAdminPromo, setAdminPromoActive, type AdminPromoDetail as PromoDetail } from "@/admin/api";
import { hasCapability } from "@/admin/capabilities";
import { AdminButton, AdminCard, AdminGate, AdminScreen } from "@/admin/AdminShell";
import { useAppTheme } from "@/components/ThemeProvider";
import { radii, type AppColors } from "@/constants/theme";

export default function AdminPromotionDetailScreen() { return <AdminGate><PromotionDetail /></AdminGate>; }

function PromotionDetail() {
  const { id } = useLocalSearchParams<{ id?: string }>();
  const { request, user } = useAdminAuth();
  const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]);
  const canWrite = Boolean(user && hasCapability(user.role, "promotions.write"));
  const [data, setData] = useState<PromoDetail | null>(null);
  const [activityPage, setActivityPage] = useState(1);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");

  const load = useCallback(async () => { if (!id) return; setLoading(true); setError(""); try { setData(await fetchAdminPromo(request, id, activityPage)); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load this promotion."); } finally { setLoading(false); } }, [activityPage, id, request]);
  useEffect(() => { const task = setTimeout(() => void load(), 0); return () => clearTimeout(task); }, [load]);

  const confirmToggle = () => { if (!data || !id) return; const next = !data.promo.is_active; Alert.alert(next ? "Activate promotion?" : "Pause promotion?", next ? "The code can become eligible immediately if its dates and redemption limits permit." : "New checkout attempts will no longer receive this discount.", [{ text: "Not now", style: "cancel" }, { text: next ? "Activate" : "Pause", style: next ? "default" : "destructive", onPress: () => void toggle(next) }]); };
  const toggle = async (next: boolean) => { if (!id) return; setBusy(true); setError(""); setNotice(""); try { await setAdminPromoActive(request, id, next); setNotice(next ? "Promotion activated." : "Promotion paused."); await load(); } catch (actionError) { setError(actionError instanceof Error ? actionError.message : "Unable to update this promotion."); } finally { setBusy(false); } };

  const promo = data?.promo;
  return <AdminScreen back eyebrow="PROMOTION DETAIL" title={promo?.code || "Promotion"} subtitle={promo ? `${promo.public_id} · ${humanize(promo.admin_state)}` : "Loading offer controls…"} refreshing={loading && Boolean(data)} onRefresh={() => void load()}>
    {loading && !data ? <AdminCard><View style={styles.skeletonLarge} /><View style={styles.skeleton} /><View style={styles.skeletonSmall} /></AdminCard> : null}
    {error ? <View style={styles.error}><MaterialIcons name="error-outline" size={20} color={colors.danger} /><Text style={styles.errorText}>{error}</Text><Pressable onPress={() => void load()}><Text style={styles.retry}>Retry</Text></Pressable></View> : null}
    {notice ? <View style={styles.notice}><MaterialIcons name="check-circle" size={20} color={colors.success} /><Text style={styles.noticeText}>{notice}</Text></View> : null}
    {data && promo ? <>
      <View style={styles.metrics}><Metric label="STATUS" value={humanize(data.summary.status)} /><Metric label="CURRENT USES" value={String(data.summary.currentCount)} /><Metric label="REMAINING" value={data.summary.remaining === null ? "Unlimited" : String(data.summary.remaining)} /><Metric label="NET DISCOUNT" value={money(Math.max(0, data.summary.totalDiscountRedeemed - data.summary.totalDiscountReversed))} /></View>
      <AdminCard><View style={styles.offerHero}><View><Text style={styles.eyebrow}>CUSTOMER OFFER</Text><Text style={styles.offerValue}>{promo.discount_type === "PERCENT" ? `${promo.discount_value}%` : money(promo.discount_value)}</Text><Text style={styles.offerScope}>{promo.apply_scope === "DAYS_TOTAL" ? "Applied to rental-days total" : "Applied to overall subtotal"}</Text></View><View style={styles.stateIcon}><MaterialIcons name={promo.admin_state === "ACTIVE" ? "local-offer" : "pause-circle-outline"} size={26} color={promo.admin_state === "ACTIVE" ? colors.success : colors.orangeDark} /></View></View><View style={styles.divider} /><Info label="Availability" value={windowLabel(promo.start_at, promo.end_at)} /><Info label="Minimum subtotal" value={promo.min_subtotal_cents === null ? "No minimum" : money(promo.min_subtotal_cents)} /><Info label="Total redemption cap" value={promo.max_redemptions === null ? "Unlimited" : String(promo.max_redemptions)} /><Info label="Per-customer cap" value={promo.max_redemptions_per_customer === null ? "Unlimited" : String(promo.max_redemptions_per_customer)} /><Info label="Allowed vehicles" value={promo.allowed_vehicle_ids_json.length ? `${promo.allowed_vehicle_ids_json.length} selected` : "All vehicles"} /><Info label="Excluded vehicles" value={promo.excluded_vehicle_ids_json.length ? `${promo.excluded_vehicle_ids_json.length} selected` : "None"} /><Info label="Blackout dates" value={promo.blackout_dates_json.length ? promo.blackout_dates_json.join(", ") : "None"} /></AdminCard>
      <AdminCard><Text style={styles.sectionTitle}>Discount activity</Text><Text style={styles.sectionBody}>{data.summary.redeemedEvents} redeemed · {data.summary.reversedEvents} reversed · {money(data.summary.totalDiscountRedeemed)} granted</Text>{data.hasReconstructedHistory ? <View style={styles.historyNote}><MaterialIcons name="history" size={17} color={colors.tealDark} /><Text style={styles.historyText}>This ledger includes reconstructed historical events. Their original timestamp source is shown where available.</Text></View> : null}<View style={styles.activityList}>{data.activity.rows.map((event) => <Pressable key={event.id} onPress={() => router.push(`/admin/bookings/${event.booking_id}` as Href)} style={styles.activity}><View style={[styles.activityIcon, event.event_type === "REVERSED" && styles.activityIconReverse]}><MaterialIcons name={event.event_type === "REVERSED" ? "undo" : "check"} size={17} color={event.event_type === "REVERSED" ? colors.orangeDark : colors.success} /></View><View style={styles.activityCopy}><Text style={styles.activityTitle}>{humanize(event.event_type)} · {money(event.discount_amount_cents)}</Text><Text style={styles.activityMeta}>{event.booking_public_id || event.booking_id.slice(0, 8).toUpperCase()} · {event.customer_email || "No email"}</Text><Text style={styles.activityTime}>{timestamp(event.event_at)}{event.is_reconstructed ? " · reconstructed" : ""}</Text></View><MaterialIcons name="chevron-right" size={20} color={colors.muted} /></Pressable>)}</View>{!data.activity.rows.length ? <Text style={styles.emptyActivity}>No redemption events have been recorded.</Text> : null}{data.activity.hasPrev || data.activity.hasNext ? <View style={styles.pager}><View style={styles.pagerButton}><AdminButton label="Previous" secondary disabled={!data.activity.hasPrev || loading} onPress={() => setActivityPage((current) => Math.max(1, current - 1))} /></View><Text style={styles.pageLabel}>{data.activity.page} / {data.activity.totalPages}</Text><View style={styles.pagerButton}><AdminButton label="Next" secondary disabled={!data.activity.hasNext || loading} onPress={() => setActivityPage((current) => current + 1)} /></View></View> : null}</AdminCard>
      {canWrite ? <AdminCard><Text style={styles.sectionTitle}>Promotion controls</Text><Text style={styles.sectionBody}>Activation is immediate but still subject to the configured dates, vehicle rules, and redemption limits.</Text><AdminButton label={busy ? "Updating…" : promo.is_active ? "Pause promotion" : "Activate promotion"} secondary onPress={confirmToggle} disabled={busy} icon={promo.is_active ? "pause" : "play-arrow"} /><AdminButton label="Edit promotion rules" secondary onPress={() => router.push(`/admin/promotions/${id}/edit` as Href)} disabled={busy} icon="edit" /></AdminCard> : null}
    </> : null}
  </AdminScreen>;
}

function Metric({ label, value }: { label: string; value: string }) { const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); return <View style={styles.metric}><Text style={styles.metricValue} numberOfLines={1} adjustsFontSizeToFit>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
function Info({ label, value }: { label: string; value: string }) { const { colors } = useAppTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); return <View style={styles.info}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>; }
function windowLabel(start: string | null, end: string | null) { if (!start && !end) return "Always available while active"; return `${start ? timestamp(start) : "Immediately"} → ${end ? timestamp(end) : "No end"}`; }
function humanize(value: string) { return value.toLowerCase().replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function timestamp(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-JM", { dateStyle: "medium", timeStyle: "short" }).format(date); }
function money(value: number) { return new Intl.NumberFormat("en-JM", { style: "currency", currency: "JMD", maximumFractionDigits: 0 }).format(Math.max(0, Number(value) || 0)); }

const makeStyles = (colors: AppColors) => StyleSheet.create({
  skeletonLarge: { width: "55%", height: 25, borderRadius: 7, backgroundColor: colors.surfaceSoft }, skeleton: { height: 16, borderRadius: 6, backgroundColor: colors.surfaceSoft, marginTop: 13 }, skeletonSmall: { width: "72%", height: 16, borderRadius: 6, backgroundColor: colors.surfaceSoft, marginTop: 10 }, error: { flexDirection: "row", alignItems: "center", gap: 8, padding: 13, borderRadius: radii.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.danger }, errorText: { flex: 1, color: colors.danger, fontSize: 11 }, retry: { color: colors.tealDark, fontSize: 10, fontWeight: "900" }, notice: { flexDirection: "row", alignItems: "center", gap: 8, padding: 13, borderRadius: radii.lg, backgroundColor: colors.cream }, noticeText: { flex: 1, color: colors.success, fontSize: 11, fontWeight: "800" },
  metrics: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, metric: { width: "48%", minHeight: 82, padding: 12, borderRadius: radii.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, metricValue: { color: colors.tealDark, fontSize: 19, fontWeight: "900" }, metricLabel: { color: colors.muted, fontSize: 8, fontWeight: "900", marginTop: 5 }, offerHero: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 12 }, eyebrow: { color: colors.muted, fontSize: 8, fontWeight: "900", letterSpacing: 1 }, offerValue: { color: colors.orange, fontSize: 31, fontWeight: "900", marginTop: 5 }, offerScope: { color: colors.muted, fontSize: 10, marginTop: 3 }, stateIcon: { width: 51, height: 51, borderRadius: 18, alignItems: "center", justifyContent: "center", backgroundColor: colors.cream }, divider: { height: 1, backgroundColor: colors.border, marginVertical: 15 }, info: { flexDirection: "row", justifyContent: "space-between", gap: 12, paddingVertical: 7 }, infoLabel: { color: colors.muted, fontSize: 11 }, infoValue: { flex: 1, color: colors.text, fontSize: 11, fontWeight: "900", textAlign: "right" },
  sectionTitle: { color: colors.text, fontSize: 18, fontWeight: "900" }, sectionBody: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 5 }, historyNote: { flexDirection: "row", gap: 7, padding: 10, borderRadius: radii.md, backgroundColor: colors.cream, marginTop: 12 }, historyText: { flex: 1, color: colors.tealDark, fontSize: 9, lineHeight: 14 }, activityList: { marginTop: 9 }, activity: { flexDirection: "row", alignItems: "center", gap: 9, paddingVertical: 11, borderBottomWidth: 1, borderBottomColor: colors.border }, activityIcon: { width: 34, height: 34, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: colors.cream }, activityIconReverse: { backgroundColor: colors.surfaceSoft }, activityCopy: { flex: 1 }, activityTitle: { color: colors.text, fontSize: 11, fontWeight: "900" }, activityMeta: { color: colors.muted, fontSize: 8, marginTop: 3 }, activityTime: { color: colors.muted, fontSize: 8, marginTop: 2 }, emptyActivity: { color: colors.muted, fontSize: 11, textAlign: "center", paddingVertical: 20 }, pager: { flexDirection: "row", alignItems: "center", gap: 9, marginTop: 12 }, pagerButton: { flex: 1 }, pageLabel: { color: colors.muted, fontSize: 9, fontWeight: "900" },
});
